name: Trigger Workflow in Repository B

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repository A
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $MY_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/ambiaahmed1/ProjectB/dispatches --data "{\"event_type\": \"trigger-external-workflow\"}"


