name: Trigger Workflow in Repository B

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repository A
        run: |
          curl -X POST -H "Authorization: token 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" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/ambiaahmed1/ProjectB/dispatches --data "{\"event_type\": \"trigger-external-workflow\"}"



